export enum onSocketsEvent {
    SET_FRIENDS_BY_NAME = 'SET_FRIENDS_BY_NAME',
}

export enum emitSocketsEvent {
    FIND_FRIENDS_BY_NAME = 'FIND_FRIENDS_BY_NAME',
    SEND_MESSAGE_IN_NEW_DIALOG = 'SEND_MESSAGE_IN_NEW_DIALOG',
    SEND_MESSAGE_IN_EXIST_DIALOG = 'SEND_MESSAGE_IN_EXIST_DIALOG'
}
