export enum onSocketsEvent {
    SET_FRIENDS_BY_NAME = 'SET_FRIENDS_BY_NAME',
    NEW_DIALOG = 'NEW_DIALOG',
    NEW_MESSAGE = 'NEW_MESSAGE',
    NEW_FRIEND_PUSH_TO_STORE = 'NEW_FRIEND_PUSH_TO_STORE',
    MESSAGE = 'MESSAGE',
    GROUP_CREATED = 'GROUP_CREATED'
}

export enum emitSocketsEvent {
    FIND_FRIENDS_BY_NAME = 'FIND_FRIENDS_BY_NAME',
    SEND_MESSAGE_IN_NEW_DIALOG = 'SEND_MESSAGE_IN_NEW_DIALOG',
    SEND_MESSAGE_IN_EXIST_DIALOG = 'SEND_MESSAGE_IN_EXIST_DIALOG',
    ADD_TO_FRIENDS = 'ADD_TO_FRIENDS',
    CREATE_GROUP = 'CREATE_GROUP'
}

export type removeSocketListenersType = {
    [key in onSocketsEvent]?: () => void
}