<template>
    <div class="loadingio-spinner-ripple-wb4dkgjke9a">
        <div class="ldio-d98rlwfllp">
            <div></div>
            <div></div>
        </div>
    </div>
</template>
<style type="text/css">
@keyframes ldio-d98rlwfllp {
    0% {
        top: 192px;
        left: 192px;
        width: 0;
        height: 0;
        opacity: 1;
    }
    100% {
        top: 104px;
        left: 104px;
        width: 176px;
        height: 176px;
        opacity: 0;
    }
}
.ldio-d98rlwfllp div {
    position: absolute;
    border-width: 8px;
    border-style: solid;
    opacity: 1;
    border-radius: 50%;
    animation: ldio-d98rlwfllp 0.8695652173913042s cubic-bezier(0, 0.2, 0.8, 1)
        infinite;
}
.ldio-d98rlwfllp div:nth-child(1) {
    border-color: #2196f3;
    animation-delay: 0s;
}
.ldio-d98rlwfllp div:nth-child(2) {
    border-color: #1760b3;
    animation-delay: -0.4347826086956521s;
}
.loadingio-spinner-ripple-wb4dkgjke9a {
    width: 400px;
    height: 400px;
    display: inline-block;
    overflow: hidden;
    background: none;
}
.ldio-d98rlwfllp {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-d98rlwfllp div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
